<?xml version="1.0"?>
<package format="3">
  <name>rc_bringup</name>
  <version>0.1.0</version>
  <description>Launch files and config for AI RC Car</description>
  <maintainer email="basvenema1992@gmail.com">Bas Venema</maintainer>
  <license>MIT</license>

  <exec_depend>rc_vehicle</exec_depend>
  <exec_depend>rc_sensors</exec_depend>
  <exec_depend>rc_mission</exec_depend>

  <buildtool_depend>ament_python</buildtool_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
